// SEARCH
export const QUERY_FETCHING = 'QUERY_FETCHING';
export const QUERY_FETCHED_SUCCEED = 'QUERY_FETCHED_SUCCEED';
export const QUERY_FETCHED_FAILED = 'QUERY_FETCHED_FAILED';

// VIDEOS
export const VIDEOS_LOADED = 'VIDEOS_LOADED';
export const VIDEOS_DIDNT_LOADED = 'VIDEOS_DIDNT_LOADED';